/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rw.gov.View;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import rw.gov.Model.Account;
import rw.gov.Model.Transaction;
import rw.gov.Service.AccountInterface;
import rw.gov.Service.TransactionInterface;

/**
 *
 * @author andre
 */
public class AdminWithdraw extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserHome
     */
    
    public AdminWithdraw() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date date  = new Date();
        String today = sdf.format(date);
        DateText.setText(today);
        DateText.setEditable(false);
    
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        names1Text = new javax.swing.JTextField();
        user1Text = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        DateText = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        acc1Text = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        balance1Text = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        amount11 = new javax.swing.JTextField();
        amount22 = new javax.swing.JTextField();
        showRamaining = new javax.swing.JButton();
        WithdrawText = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setPreferredSize(new java.awt.Dimension(610, 460));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cash Withdraw");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 25));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("User :");

        jLabel6.setText("Names :");

        names1Text.setEditable(false);

        jLabel8.setText("Date :");

        DateText.setEditable(false);

        searchBtn.setBackground(new java.awt.Color(102, 0, 102));
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Account No :");

        acc1Text.setEditable(false);

        jLabel10.setText("Available Balance ;");

        balance1Text.setEditable(false);

        jLabel11.setText("Withdraw Amout :");

        amount22.setEditable(false);

        showRamaining.setText("Show");
        showRamaining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRamainingActionPerformed(evt);
            }
        });

        WithdrawText.setBackground(new java.awt.Color(102, 0, 102));
        WithdrawText.setForeground(new java.awt.Color(255, 255, 255));
        WithdrawText.setText("Withdraw");
        WithdrawText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawTextActionPerformed(evt);
            }
        });

        jLabel7.setText("Total :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(DateText, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(193, 193, 193)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(names1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(124, 124, 124))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(WithdrawText, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(11, 11, 11)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(amount11, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                                .addComponent(amount22)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32)
                                                .addComponent(user1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel10))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(balance1Text)
                                                    .addComponent(acc1Text, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))))))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(showRamaining)
                                    .addComponent(searchBtn))))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(names1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(acc1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(balance1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(amount11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showRamaining)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(amount22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(WithdrawText)
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 360, 380));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rw/gov/View/bankbg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 660, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
//        int accountNumber = Integer.parseInt(user1Text.getText());
//        //          String firstName  = userText.getText();
//
//
//        if (searchUser != null) {
//            names1Text.setText(searchUser.getFirst_name() + " " + searchUser.getLast_name());
//            acc1Text.setText(String.valueOf(searchUser.getAccount_nbr()));
//            balance1Text.setText(String.valueOf(searchUser.getAmount()));
//
//            // Set other fields as needed
//        } else {
//            // Handle case where account is not found
//            JOptionPane.showMessageDialog(this, "User not found", "Error", JOptionPane.ERROR_MESSAGE);
//        }
         try {
            int accountNumber;
             try {
                 accountNumber = Integer.parseInt(user1Text.getText());
                 
             } catch (Exception e) {
                 JOptionPane.showMessageDialog(this, "Invalid account number format.", "Error", JOptionPane.ERROR_MESSAGE);
                  return;
             }
             
              Registry registry = LocateRegistry.getRegistry("127.0.0.1", 6000);
              AccountInterface intrf = (AccountInterface) registry.lookup("account");
              
              Account searchUser = intrf.getAccountByNumber(accountNumber);
              if(searchUser != null){
                names1Text.setText(searchUser.getFirst_name() + "" + searchUser.getLast_name());
                acc1Text.setText(String.valueOf(searchUser.getAccount_nbr()));
                balance1Text.setText(String.valueOf(searchUser.getAmount()));
                
              
              }else {
            JOptionPane.showMessageDialog(this, "Account not found", "Error", JOptionPane.ERROR_MESSAGE);
             }
              
              
        } catch (Exception e) {
            e.printStackTrace();
        }



    }//GEN-LAST:event_searchBtnActionPerformed

    private void showRamainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRamainingActionPerformed
        // TODO add your handling code here:
         try {
            Double withdrawAmount = Double.parseDouble(amount11.getText());
            Double currentAmount = Double.parseDouble(balance1Text.getText());

            if (withdrawAmount <= 0) {
                JOptionPane.showMessageDialog(this, "Withdraw amount must be greater than zero", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (withdrawAmount <= currentAmount) {
                Double totalAmount = currentAmount - withdrawAmount;
                amount22.setText(String.valueOf(totalAmount));
            } else {
                JOptionPane.showMessageDialog(this, "Insufficient balance", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid input format", "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_showRamainingActionPerformed

    private void WithdrawTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawTextActionPerformed
        // TODO add your handling code here:

         int id = Integer.parseInt(acc1Text.getText());
         Double newAmount = Double.parseDouble(amount22.getText());
         Account theAccount = new Account();
         theAccount.setAccount_nbr(id);
         theAccount.setAmount(newAmount);
         try {
             Registry reg = LocateRegistry.getRegistry("127.0.0.1", 6000);
             AccountInterface acc = (AccountInterface) reg.lookup("account");
             TransactionInterface tx = (TransactionInterface) reg.lookup("transaction");
             

             String feedback = acc.updateAccountAmount(theAccount);
             
             Double depositAmount = Double.parseDouble(amount11.getText());
             
//             int accountId = Long.parseLong(id); // assuming id is a String, convert it to Long
             Account account = acc.getAccountByNumber(id);
     
             Transaction transaction = new Transaction();
             transaction.setAccount(account); 
             transaction.setAmount(depositAmount);
             transaction.setType("Withdraw");
             transaction.setTimestamp(new Date());
             String txFeedback = tx.registerTransaction(transaction);
             
              if (feedback.equalsIgnoreCase("Amount Updated successfully.")){
                   JOptionPane.showMessageDialog(this, "Withdraw successful!!", "Feedback", JOptionPane.INFORMATION_MESSAGE);
                   System.out.println("don't know if they are saved in transaction check for your self");
                   clearFields();
                 }
            else{
                   JOptionPane.showMessageDialog(this, feedback, "Error", JOptionPane.ERROR_MESSAGE);
                 }
        } catch (Exception e) {
            e.printStackTrace();
        }
       
        
    }//GEN-LAST:event_WithdrawTextActionPerformed


    public void clearFields(){
      amount11.setText("");
      names1Text.setText("");
      acc1Text.setText("");
      balance1Text.setText("");
      amount22.setText("");
      user1Text.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DateText;
    private javax.swing.JButton WithdrawText;
    private javax.swing.JTextField acc1Text;
    private javax.swing.JTextField amount11;
    private javax.swing.JTextField amount22;
    private javax.swing.JTextField balance1Text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField names1Text;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton showRamaining;
    private javax.swing.JTextField user1Text;
    // End of variables declaration//GEN-END:variables
}
