/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rw.gov.View;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import rw.gov.Model.Account;
import rw.gov.Model.Transaction;
import rw.gov.Service.AccountInterface;

/**
 *
 * @author andre
 */
public class DeleteAccount extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserHome
     */
    
    public DeleteAccount() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        
//        this.accountNumber = accountNumber;
//        
//        youraccount.setText(String.valueOf(accountNumber));

        
        
    }

//    AdminDeposit() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userText = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setPreferredSize(new java.awt.Dimension(610, 460));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Delete Account");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 25));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("User :");

        delete.setBackground(new java.awt.Color(102, 0, 102));
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(delete)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(delete)
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 360, 170));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rw/gov/View/bankbg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 660, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
//      try {
//        int accountNumber;
//        try {
//            accountNumber = Integer.parseInt(userText.getText());
//        } catch (NumberFormatException ex) {
//            JOptionPane.showMessageDialog(this, "Invalid account number format.", "Error", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//
//        Registry registry = LocateRegistry.getRegistry("127.0.0.1", 6000);
//        AccountInterface intrf = (AccountInterface) registry.lookup("account");
//
//        Account searchUser = intrf.getAccountByNumber(accountNumber);
//        if (searchUser != null) {
//            int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete " + searchUser.getFirst_name() + "?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
//
//            if (option == JOptionPane.YES_OPTION) {
//                String feedback = intrf.deleteAccount(searchUser.getAccount_nbr());
//                System.out.println("Data Deleted Successfully");
//                if(feedback.equalsIgnoreCase("Data Deleted Successfully")){
//                   JOptionPane.showMessageDialog(this, feedback, "FeedBack",JOptionPane.INFORMATION_MESSAGE);
//                }
//                 else{
//                   JOptionPane.showMessageDialog(this, feedback,"Feedback",JOptionPane.ERROR_MESSAGE);
//                }
//            
//            } else {
//                System.out.println("Deletion cancelled.");
//            }
//
//        } else {
//            JOptionPane.showMessageDialog(this, "Account not found", "Error", JOptionPane.ERROR_MESSAGE);
//        }
//
//    } catch (Exception e) {
//        e.printStackTrace();
//    }

         try {
            int accountNumber;
            try {
                accountNumber = Integer.parseInt(userText.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Invalid account number format.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Registry registry = LocateRegistry.getRegistry("127.0.0.1", 6000);
            AccountInterface intrf = (AccountInterface) registry.lookup("account");

            Account searchUser = intrf.getAccountByNumber(accountNumber);
            if (searchUser != null) {
                int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete " + searchUser.getFirst_name() + "?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);

                if (option == JOptionPane.YES_OPTION) {
                    String feedback = intrf.deleteAccountByAccountNumber(searchUser.getAccount_nbr());
                    System.out.println(feedback);
                    if(feedback.equalsIgnoreCase("Data Deleted Successfully")){
                       JOptionPane.showMessageDialog(this, feedback, "FeedBack", JOptionPane.INFORMATION_MESSAGE);
                       userText.setText("");
                    } else {
                       JOptionPane.showMessageDialog(this, feedback,"Feedback", JOptionPane.ERROR_MESSAGE);
                        userText.setText("");
                    }
                
                } else {
                    System.out.println("Deletion cancelled.");
                     userText.setText("");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Account not found", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_deleteActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables
}
