/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rw.gov.View;

import java.awt.Color;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
//import rw.gov.View.Login_Apps1;

/**
 *
 * @author andre
 */
public class Home extends javax.swing.JDialog {

    /**
     * Creates new form Home
     */
    
    Color DefaultColor, ClickedColor;
    private String username;
    private int accountNumber;
    

    
    public Home(java.awt.Frame parent, boolean modal, String username, int accountNumber) {
               
        super(parent, modal);
        initComponents();
         
        this.username = username;
        this.accountNumber = accountNumber;
        
        
        userprofile.setText(username);
        
        DefaultColor = new Color(134, 68, 162);
        ClickedColor = new Color(153, 0, 153);
        
        //set default color
        
        home.setBackground(DefaultColor);
        deposit.setBackground(DefaultColor);
        withdraw.setBackground(DefaultColor);
        transfer.setBackground(DefaultColor);
        viewbalance.setBackground(DefaultColor);
    }

    Home() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

//    private Home(JFrame jFrame, boolean b) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        X = new javax.swing.JLabel();
        sidepanel = new javax.swing.JPanel();
        sidepanel1 = new javax.swing.JPanel();
        deposit = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        viewbalance = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        withdraw = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        transfer = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        userprofile = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        logout = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        content = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        bg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        X.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        X.setForeground(new java.awt.Color(255, 0, 51));
        X.setText("X");
        X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XMouseClicked(evt);
            }
        });
        bg.add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, 30));

        sidepanel.setBackground(new java.awt.Color(12, 53, 158));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel1.setBackground(new java.awt.Color(134, 68, 162));
        sidepanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deposit.setBackground(new java.awt.Color(134, 68, 162));
        deposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                depositMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                depositMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                depositMousePressed(evt);
            }
        });
        deposit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\andre\\Downloads\\icons8-deposit-color\\icons8-deposit-24.png")); // NOI18N
        deposit.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 20, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Deposit");
        deposit.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 180, 30));

        sidepanel1.add(deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 260, 50));

        viewbalance.setBackground(new java.awt.Color(134, 68, 162));
        viewbalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewbalanceMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewbalanceMousePressed(evt);
            }
        });
        viewbalance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\andre\\Downloads\\icons8-balance-pieces\\icons8-balance-24.png")); // NOI18N
        viewbalance.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 20, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("BalanceEnquiry");
        viewbalance.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 180, 30));

        sidepanel1.add(viewbalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 270, 50));

        withdraw.setBackground(new java.awt.Color(134, 68, 162));
        withdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                withdrawMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                withdrawMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                withdrawMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                withdrawMousePressed(evt);
            }
        });
        withdraw.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\andre\\Downloads\\icons8-withdrawal-16.png")); // NOI18N
        withdraw.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 20, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Withdraw");
        withdraw.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 180, 30));

        sidepanel1.add(withdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 270, 50));

        transfer.setBackground(new java.awt.Color(134, 68, 162));
        transfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transferMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                transferMousePressed(evt);
            }
        });
        transfer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\andre\\Downloads\\icons8-transfer-16.png")); // NOI18N
        transfer.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 20, 30));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Transfer");
        transfer.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 180, 30));

        sidepanel1.add(transfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 270, 50));

        home.setBackground(new java.awt.Color(134, 68, 162));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
        });
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\andre\\Downloads\\icons8-summary-list-pulsar-gradient\\icons8-summary-list-24.png")); // NOI18N
        home.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Account Summary");
        home.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 170, 30));

        sidepanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 270, 50));

        jPanel2.setBackground(new java.awt.Color(134, 68, 162));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.setIcon(new javax.swing.ImageIcon("C:\\Users\\andre\\Downloads\\icons8-user-profile-32.png")); // NOI18N
        jPanel2.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 50));

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Welcome,");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        userprofile.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        userprofile.setForeground(new java.awt.Color(204, 204, 204));
        userprofile.setText("Andrew");
        userprofile.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(userprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 70, 30));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 78, 170, -1));

        sidepanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, 120));

        logout.setBackground(new java.awt.Color(134, 68, 162));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rw/gov/View/icons8-logout-24.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Logout");

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 110, 50));

        sidepanel.add(sidepanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -10, 260, 530));

        bg.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, 510));

        content.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        content.setForeground(new java.awt.Color(255, 0, 0));
        content.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rw/gov/View/bankbg.jpg"))); // NOI18N
        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 640, 510));

        jLabel9.setText("jLabel9");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        // TODO add your handling code here

    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        // TODO add your handling code here:
 
    }//GEN-LAST:event_homeMouseExited

    private void depositMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositMouseEntered
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_depositMouseEntered

    private void depositMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_depositMouseExited

    private void withdrawMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawMouseEntered

    private void withdrawMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawMouseExited

    }//GEN-LAST:event_withdrawMouseExited

    private void transferMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferMouseEntered
        // TODO add your handling code here:
                              
    }//GEN-LAST:event_transferMouseEntered

    private void homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMousePressed
        // TODO add your handling code here:
        home.setBackground(ClickedColor);
        deposit.setBackground(DefaultColor);
        withdraw.setBackground(DefaultColor);
        transfer.setBackground(DefaultColor);
        viewbalance.setBackground(DefaultColor);
    }//GEN-LAST:event_homeMousePressed

    private void depositMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositMousePressed
        // TODO add your handling code here:
        home.setBackground(DefaultColor);
        deposit.setBackground(ClickedColor);
        withdraw.setBackground(DefaultColor);
        transfer.setBackground(DefaultColor);
        viewbalance.setBackground(DefaultColor);
    }//GEN-LAST:event_depositMousePressed

    private void withdrawMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawMousePressed
        // TODO add your handling code here:
        home.setBackground(DefaultColor);
        deposit.setBackground(DefaultColor);
        withdraw.setBackground(ClickedColor);
        transfer.setBackground(DefaultColor);
        viewbalance.setBackground(DefaultColor);
    }//GEN-LAST:event_withdrawMousePressed

    private void transferMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferMousePressed
        // TODO add your handling code here:
         home.setBackground(DefaultColor);
        deposit.setBackground(DefaultColor);
        withdraw.setBackground(DefaultColor);
        transfer.setBackground(ClickedColor);
        viewbalance.setBackground(DefaultColor);
    }//GEN-LAST:event_transferMousePressed

    private void viewbalanceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewbalanceMousePressed
        // TODO add your handling code here:
        home.setBackground(DefaultColor);
        deposit.setBackground(DefaultColor);
        withdraw.setBackground(DefaultColor);
        transfer.setBackground(DefaultColor);
        viewbalance.setBackground(ClickedColor);
    }//GEN-LAST:event_viewbalanceMousePressed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        UserHome userhome = new UserHome(accountNumber);
        content.removeAll(); 
        content.add(userhome); 
        userhome.setVisible(true);
    }//GEN-LAST:event_homeMouseClicked

    private void depositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositMouseClicked
        // TODO add your handling code here:
        UserDeposit userdeposit = new UserDeposit(accountNumber);
        content.removeAll(); 
        content.add(userdeposit); 
        userdeposit.setVisible(true);
        
//        youraccount.setText();
    }//GEN-LAST:event_depositMouseClicked

    private void withdrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawMouseClicked
        // TODO add your handling code here:
        UserWithdraw userWithdraw = new UserWithdraw(accountNumber);
        content.removeAll(); 
        content.add(userWithdraw); 
        userWithdraw.setVisible(true);
    }//GEN-LAST:event_withdrawMouseClicked

    private void transferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferMouseClicked
        // TODO add your handling code here:
        UserTransfer usertransfer= new UserTransfer(accountNumber);
        content.removeAll(); 
        content.add(usertransfer); 
        usertransfer.setVisible(true); 
    }//GEN-LAST:event_transferMouseClicked

    private void viewbalanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewbalanceMouseClicked
        // TODO add your handling code here:
     try {
        // Your code that might throw NotBoundException
        ViewBalance viewbalance= new ViewBalance(accountNumber);
        content.removeAll(); 
        content.add(viewbalance); 
        viewbalance.setVisible(true);
    } catch (java.rmi.NotBoundException ex) {
        // Handle the exception or log it
        ex.printStackTrace(); // Example of logging the exception
    }
    }//GEN-LAST:event_viewbalanceMouseClicked

    private void XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseClicked
        // TODO add your handling code here:
        
         int confirmation = JOptionPane.showConfirmDialog(null, "Do you really want to Logout?", "Select", JOptionPane.YES_NO_OPTION); 
        if (confirmation == JOptionPane.YES_OPTION) {
            this.dispose();
            
            openLogoutDialog();
             
    }  
        
    }//GEN-LAST:event_XMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
         int confirmation = JOptionPane.showConfirmDialog(null, "Do you really want to Logout?", "Select", JOptionPane.YES_NO_OPTION); 
        if (confirmation == JOptionPane.YES_OPTION) {
            this.dispose();
            
            openLogoutDialog();
             
    }  
    }//GEN-LAST:event_logoutMouseClicked

    private void openLogoutDialog() {
        LoginPage loginDialog = new LoginPage(new javax.swing.JFrame(), true);
        loginDialog.setVisible(true);

        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nbgintroduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
           ex.printStackTrace();
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home dialog = new Home();                
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel X;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel content;
    private javax.swing.JPanel deposit;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel logout;
    private javax.swing.JLabel profile;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JPanel sidepanel1;
    private javax.swing.JPanel transfer;
    private javax.swing.JLabel userprofile;
    private javax.swing.JPanel viewbalance;
    private javax.swing.JPanel withdraw;
    // End of variables declaration//GEN-END:variables

    private void closeCurrentPage() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
