/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rw.gov.View;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import rw.gov.Model.Account;
import rw.gov.Model.Transaction;
import rw.gov.Service.AccountInterface;
import rw.gov.Service.TransactionInterface;

/**
 *
 * @author andre
 */
public class UserTransfer extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserHome
     */
    
    private int accountNumber;
    
    public UserTransfer(int accountNumber) {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        this.accountNumber = accountNumber;
        youraccount.setText(String.valueOf(accountNumber));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        youraccount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        selectAccount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        amountText = new javax.swing.JTextField();
        transferBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(620, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Make a Transaction");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Transfer Money");

        jLabel4.setText("Your Account:");

        youraccount.setEditable(false);

        jLabel5.setText("Select Account:");

        jLabel6.setText("Amount :");

        transferBtn.setBackground(new java.awt.Color(102, 0, 102));
        transferBtn.setForeground(new java.awt.Color(255, 255, 255));
        transferBtn.setText("Transfer");
        transferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(youraccount)
                            .addComponent(selectAccount)
                            .addComponent(amountText, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(transferBtn, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(youraccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(transferBtn)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 440, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rw/gov/View/bankbg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 690, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferBtnActionPerformed
        // TODO add your handling code here:
        try {
    
        Double transferAmount = Double.parseDouble(amountText.getText());
        int senderAccountNumber = accountNumber; 
        int receiverAccountNumber = Integer.parseInt(selectAccount.getText());
        
        
         Registry reg = LocateRegistry.getRegistry("127.0.0.1", 6000);
         AccountInterface acc = (AccountInterface) reg.lookup("account");
         TransactionInterface tx = (TransactionInterface) reg.lookup("transaction");
         
         
         //this is for the user of account
         Account searchUser = acc.getAccountByNumber(senderAccountNumber);
         int userAccount = searchUser.getAccount_nbr();
         Double userAmount = searchUser.getAmount();
         Double userRemainingAmount = userAmount - transferAmount;
         
         //set it in the database now
         
         Account account = new Account();
         account.setAccount_nbr(userAccount);
         account.setAmount(userRemainingAmount);
         
         
         //this is for reciever of the amount
         
         Account searchReciever= acc.getAccountByNumber(receiverAccountNumber);

         if(searchReciever != null){
             int recieverAccount = searchReciever.getAccount_nbr();
             Double recieverAmount = searchReciever.getAmount();   
             Double recieverRemainingAmount = recieverAmount + transferAmount;

             //set it in the database now

             Account theAccount = new Account();
             theAccount.setAccount_nbr(recieverAccount);
             theAccount.setAmount(recieverRemainingAmount);



             String feedback = acc.updateAccountAmount(theAccount);
             String feedback2 = acc.updateAccountAmount(account);
             
             //now let's log transaction
             Account accountt = acc.getAccountByNumber(senderAccountNumber); 
             
             Transaction transaction = new Transaction();
             transaction.setAccount(accountt); 
             transaction.setAmount(transferAmount);
             transaction.setType("Transfer");
             transaction.setTimestamp(new Date());
             String txFeedback = tx.registerTransaction(transaction);
             
             //also message for receiver account
             
             Account receiverAccount = acc.getAccountByNumber(receiverAccountNumber); 
             
             Transaction recieverTransaction = new Transaction();
             recieverTransaction.setAccount(receiverAccount); 
             recieverTransaction.setAmount(transferAmount);
             recieverTransaction.setType("recieved");
             recieverTransaction.setTimestamp(new Date());
             String recieverFeedback = tx.registerTransaction(recieverTransaction);
             
             
             if (feedback.equalsIgnoreCase("Amount Updated successfully.")){
                   JOptionPane.showMessageDialog(this, "Transfer successful!!", "Feedback", JOptionPane.INFORMATION_MESSAGE);
                 }
             else{
                   JOptionPane.showMessageDialog(this, feedback, "Error", JOptionPane.ERROR_MESSAGE);
                 }
        }else{
            JOptionPane.showMessageDialog(this, "Account does not exist", "Feedback", JOptionPane.INFORMATION_MESSAGE);
        }
        
        JOptionPane.showMessageDialog(this, "Transfer Successful");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid input for amount or account number", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Transfer Failed", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_transferBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField selectAccount;
    private javax.swing.JButton transferBtn;
    private javax.swing.JTextField youraccount;
    // End of variables declaration//GEN-END:variables
}
