/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rw.gov.View;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import rw.gov.Model.Account;
import rw.gov.Model.Transaction;
import rw.gov.Service.AccountInterface;
import rw.gov.Service.TransactionInterface;

/**
 *
 * @author andre
 */
public class UserDeposit extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserHome
     */
    private int accountNumber;
    
    public UserDeposit(int accountNumber) {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        this.accountNumber = accountNumber;
        
        youraccount.setText(String.valueOf(accountNumber));

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        amountText = new javax.swing.JTextField();
        depositBtn = new javax.swing.JButton();
        youraccount = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setPreferredSize(new java.awt.Dimension(620, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Credit Account");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Cash Deposit");

        jLabel3.setText("Your Account");

        jLabel6.setText("Amount");

        depositBtn.setBackground(new java.awt.Color(102, 0, 102));
        depositBtn.setForeground(new java.awt.Color(255, 255, 255));
        depositBtn.setText("Deposit");
        depositBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositBtnActionPerformed(evt);
            }
        });

        youraccount.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(amountText, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(youraccount))
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(depositBtn)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(youraccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(depositBtn)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 580, 230));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rw/gov/View/bankbg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 720, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositBtnActionPerformed
        // TODO add your handling code here:
        try {           
            String amountStr = amountText.getText();
            if (amountStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter the amount", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            double newAmount = Double.parseDouble(amountStr);

            String accountNumberStr = youraccount.getText();
            if (accountNumberStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Account number is empty", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int getAccountNumber;
            try {
                getAccountNumber = Integer.parseInt(accountNumberStr);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Invalid account number format", "Error", JOptionPane.ERROR_MESSAGE);
                return; 
            }

            
            Registry reg = LocateRegistry.getRegistry("127.0.0.1", 6000);
            AccountInterface acc = (AccountInterface) reg.lookup("account");
            TransactionInterface tx = (TransactionInterface) reg.lookup("transaction");

            
            Account searchUser = acc.getAccountByNumber(accountNumber);
            Double currentAmount = searchUser.getAmount();
            Double depositAmount = currentAmount + newAmount;
            
            Account theAccount = new Account();
            theAccount.setAccount_nbr(getAccountNumber);
            theAccount.setAmount(depositAmount);
           
            String feedback = acc.updateAccountAmount(theAccount);
            
            Account account = acc.getAccountByNumber(getAccountNumber);
            
            Transaction transaction = new Transaction();
            transaction.setAccount(account); 
            transaction.setAmount(newAmount);
            transaction.setType("Deposit");
            transaction.setTimestamp(new Date());
            String txFeedback = tx.registerTransaction(transaction);
            if (feedback.equalsIgnoreCase("Amount Updated successfully.")){
              JOptionPane.showMessageDialog(this, "Deposited successful!!", "Feedback", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
               JOptionPane.showMessageDialog(this, feedback, "Error", JOptionPane.ERROR_MESSAGE);
            }

//            JOptionPane.showMessageDialog(this, "Deposit Successful");
            amountText.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input for amount", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Deposit Failed", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_depositBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountText;
    private javax.swing.JButton depositBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField youraccount;
    // End of variables declaration//GEN-END:variables
}
