/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rw.gov.View;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import rw.gov.Model.Account;
import rw.gov.Model.Transaction;
import rw.gov.Service.AccountInterface;
import rw.gov.Service.TransactionInterface;

/**
 *
 * @author andre
 */
public class UserWithdraw extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserHome
     */
    
    private int accountNumber;
    
    public UserWithdraw( int accountNumber) {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        this.accountNumber = accountNumber;
        youraccount.setText(String.valueOf(accountNumber));

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        youraccount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        amountText = new javax.swing.JTextField();
        withdrawBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(620, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Debit Account");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Cash Withdraw");

        jLabel3.setText("Your Account :");

        youraccount.setEditable(false);

        jLabel4.setText("Amount :");

        withdrawBtn.setBackground(new java.awt.Color(102, 0, 102));
        withdrawBtn.setForeground(new java.awt.Color(255, 255, 255));
        withdrawBtn.setText("Withdraw");
        withdrawBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(youraccount, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(withdrawBtn))))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(youraccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(withdrawBtn)
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 540, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rw/gov/View/bankbg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 752, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawBtnActionPerformed
        // TODO add your handling code here:
        try {           
           String amountStr = amountText.getText();
          if (amountStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the withdrawal amount", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        double newAmount = Double.parseDouble(amountStr);

        // Validate the account number input
        String accountNumberStr = youraccount.getText();
        if (accountNumberStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Account number is empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
           int accountNumber = Integer.parseInt(accountNumberStr);

            Registry reg = LocateRegistry.getRegistry("127.0.0.1", 6000);
            AccountInterface acc = (AccountInterface) reg.lookup("account");
            TransactionInterface tx = (TransactionInterface) reg.lookup("transaction");
              
            Account searchUser = acc.getAccountByNumber(accountNumber);
            Double currentAmount = searchUser.getAmount();
            if(currentAmount > newAmount){
               Double depositAmount = currentAmount - newAmount;
               Account theAccount = new Account();
               theAccount.setAccount_nbr(accountNumber);
               theAccount.setAmount(depositAmount);
           
               String feedback = acc.updateAccountAmount(theAccount);
               
                Account account = acc.getAccountByNumber(accountNumber);
            
                Transaction transaction = new Transaction();
                transaction.setAccount(account); 
                transaction.setAmount(newAmount);
                transaction.setType("Withdraw");
                transaction.setTimestamp(new Date());
                String txFeedback = tx.registerTransaction(transaction);
               
               if (feedback.equalsIgnoreCase("Amount Updated successfully.")){
                 JOptionPane.showMessageDialog(this, "Withdraw successful!!", "Feedback", JOptionPane.INFORMATION_MESSAGE);
                 }
              else{
                 JOptionPane.showMessageDialog(this, feedback, "Error", JOptionPane.ERROR_MESSAGE);
                 }
                 }
            else{
              JOptionPane.showMessageDialog(this, "Unsufficient balance", "Error", JOptionPane.ERROR_MESSAGE);
 
            }
            
        amountText.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input for amount", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Withdraw Failed", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error during withdrawal: " + e.getMessage());
            e.printStackTrace(); // Print the full stack trace for debugging
        }
    }//GEN-LAST:event_withdrawBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton withdrawBtn;
    private javax.swing.JTextField youraccount;
    // End of variables declaration//GEN-END:variables
}
