/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rw.gov.View;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.text.MessageFormat;
import java.util.List;
import java.util.Vector;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import rw.gov.Model.Account;
import rw.gov.Model.Transaction;
import rw.gov.Service.AccountInterface;
import rw.gov.Service.TransactionInterface;

/**
 *
 * @author andre
 */
public class UserHome extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserHome
     */
      DefaultTableModel model = new DefaultTableModel();

    
    private int accountNumber;
    public UserHome(int accountNumber) {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        this.accountNumber = accountNumber;
        
        
        initializeTableModel();
//        addRows();
        
        try {
             Registry reg = LocateRegistry.getRegistry("127.0.0.1", 6000);
             AccountInterface acc = (AccountInterface) reg.lookup("account");
             
             Account searchUser = acc.getAccountByNumber(accountNumber);
             welcomeText.setText(searchUser.getFirst_name());
             balance.setText(searchUser.getAmount().toString());
             addRows();
                   
        } catch (Exception e) {
            e.printStackTrace();
        }
        
      
        
        
        
    }
    
    
     public void initializeTableModel() {
        model.addColumn("Date");
        model.addColumn("Transaction_Type");
        model.addColumn("Amount");
        
        balanceTable.setModel(model);
        
     } 
        
     public void addRows() {
            try {
             Registry reg=LocateRegistry.getRegistry("127.0.0.1", 6000);
             TransactionInterface tra = (TransactionInterface) reg.lookup("transaction");
             List<Transaction> transaction= tra.getTransactionsByAccountNumber(accountNumber);
             DefaultTableModel recodedTable = (DefaultTableModel)balanceTable.getModel();
             recodedTable.setRowCount(0);
             Vector columnData = null;
             
             if(transaction != null)
            {
            for(Transaction item: transaction)
            {                
                columnData = new Vector();
                columnData.add(item.getTimestamp());
                columnData.add(item.getType());             
                columnData.add(item.getAmount()); 
                
                System.out.println("Account ID: " + item.getAccount());
                

                recodedTable.addRow(columnData);

            }
        }
         } catch (Exception e) {
             e.printStackTrace();
         }
        }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        printpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        balance = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        balanceTable = new javax.swing.JTable();
        welcomeText = new javax.swing.JTextField();
        print = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(620, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        printpanel.setBackground(new java.awt.Color(255, 255, 255));
        printpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Statement");
        printpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 20));

        jLabel3.setText("Welcome :");
        printpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 60, 20));

        jLabel5.setText("Available Balance:");
        printpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));
        printpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 100, -1));

        balance.setEditable(false);
        balance.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        printpanel.add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 90, 30));

        balanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(balanceTable);

        printpanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 430, 130));

        welcomeText.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        printpanel.add(welcomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 90, 30));

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        printpanel.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        getContentPane().add(printpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 500, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rw/gov/View/bankbg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
      MessageFormat header = new MessageFormat("Account Summary");
      MessageFormat footer = new MessageFormat("End");
    
      try {
        PrintRequestAttributeSet set = new HashPrintRequestAttributeSet();
        set.add(OrientationRequested.PORTRAIT);
        
        // Replace customerTable with your actual table name
        balanceTable.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, set, true);
     } catch (PrinterException pe) {
        pe.printStackTrace();
    }
      
    }//GEN-LAST:event_printActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balance;
    private javax.swing.JTable balanceTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton print;
    private javax.swing.JPanel printpanel;
    private javax.swing.JTextField welcomeText;
    // End of variables declaration//GEN-END:variables
}
